export const mockupData = [
  { id: 3 },
  { id: 3 },
  { id: 2 },
  { id: 0 },
  { id: 5 },
  { id: 3 },
  { id: 1 },
  { id: 5 },
  { id: 4 },
  { id: 7 },
  { id: 6 },
  { id: 7 },
  { id: null, today: true },
  { id: null },
  { id: null },
  { id: null },
  { id: null },
  { id: null },
  { id: null },
  { id: null },
  { id: null },
  { id: null },

]