export enum DailyArticleActionTypes {
  REQUEST_DAILY_ARTICLE = 'dailyArticle/REQUEST_DAILY_ARTICLE',
  SUCCESS_DAILY_ARTICLE = 'dailyArticle/SUCCESS_DAILY_ARTICLE',
  FAILURE_DAILY_ARTICLE = 'dailyArticle/FAILURE_DAILY_ARTICLE',
  REQUEST_SAVE_DAILY_ARTICLE = 'dailyArticle/REQUEST_SAVE_DAILY_ARTICLE',
  SUCCESS_SAVE_DAILY_ARTICLE = 'dailyArticle/SUCCESS_SAVE_DAILY_ARTICLE',
  FAILURE_SAVE_DAILY_ARTICLE = 'dailyArticle/FAILURE_SAVE_DAILY_ARTICLE',
}
